baseURL: "https://percona.community/"
disablePathToLower: false
languageCode: "en-us"
title: "Percona Community"
copyright: |
  Â© Percona Community. MySQL, InnoDB, MariaDB and MongoDB are trademarks of their respective owners.
disableHugoGeneratorInject: true
params:
  favicon: superhero.png
  images:
    - contribute.png
taxonomies:
  tag: tags
social:
  twitter: Percona
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 1
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: monokai
    tabWidth: 4
menu:
  main:
    - identifier: MongoDB
      name: MongoDB
      url: /mongodb
      weight: 1
    - identifier: MySQL
      name: MySQL
      url: /mysql
      weight: 2
    - identifier: PostgreSQL
      name: PostgreSQL
      url: /postgresql
      weight: 3
    - identifier: projects
      name: Projects
      url: /projects
      weight: 4
    - identifier: podcasts
      name: Podcasts
      url: /podcasts
      weight: 5
    - identifier: events
      name: Events
      url: /events
      weight: 6
    - identifier: blog
      name: Blog
      url: /blog
      weight: 7
    - identifier: contribute
      name: Contribute
      url: /contribute
      weight: 8

    - identifier: hoss
      name: HOSS Talks
      url: /podcasts/
      parent: podcasts
      weight: 1
    - identifier: dsto
      name: Dave Stokes
      url: /events/dave-stokes-talks-open-percona-live-2022/
      parent: podcasts
      weight: 2

    - identifier: kubernetes
      name: Kubernetes Operators
      url: /projects/operators/
      parent: projects
      weight: 1
    - identifier: pmm
      name: Percona Monitoring and Management
      url: /projects/pmm/
      parent: projects
      weight: 2
    - identifier: subtoolkit
      name: Percona Toolkit
      url: /projects/toolkit/
      parent: projects
      weight: 3
    - identifier: allprojects
      name: All projects
      url: /projects
      parent: projects
      weight: 4

    - identifier: communityevents
      name: Community Events
      url: /events
      parent: events
      weight: 1
    - identifier: engineeringmeetings
      name: Engineering Meetings
      url: /contribute/engineeringmeetings
      parent: events
      weight: 2
    - identifier: speakers
      name: Speakers
      url: /speakers
      parent: events
      weight: 3

    - identifier: posts
      name: Posts
      url: /blog
      parent: blog
      weight: 1
    - identifier: authors
      name: Authors
      url: /authors
      parent: blog
      weight: 2

    - identifier: articles
      name: Articles
      url: /contribute/articles
      parent: contribute
      weight: 1
    - identifier: youtube_playlists
      name: YouTube Playlists
      url: /contribute/youtube_playlists
      parent: contribute
      weight: 3
    - identifier: coc
      name: Code of Conduct
      url: /contribute/coc
      parent: contribute
      weight: 6
    - identifier: documentation
      name: Documentation
      url: /contribute/documentation
      parent: contribute
      weight: 7
    - identifier: opentopics
      name: Open Topics
      url: /contribute/opentopics
      parent: contribute
      weight: 2
    - identifier: emm
      name: Engineering Meetings
      url: /contribute/engineeringmeetings
      parent: contribute
      weight: 4
    - identifier: surveys
      name: Testimonials & Surveys
      url: /contribute/testimonials
      parent: contribute
      weight: 5
    - identifier: help
      name: Help Wanted
      url: /contribute/help-wanted
      parent: contribute
      weight: 8
    - identifier: videos
      name: Videos
      url: /contribute/videos
      parent: contribute
      weight: 9

  footer:
    - identifier: about
      name: About
      url: https://www.percona.com/about-percona
      weight: 1
    - identifier: legal
      name: Legal
      url: https://www.percona.com/legal
      weight: 2
    - identifier: contact
      name: Contact
      url: https://www.percona.com/about-percona/contact
      weight: 3
    - identifier: forums
      name: Forums
      url: https://forums.percona.com
      weight: 4
    - identifier: discord
      name: Discord
      url: http://per.co.na/discord
      weight: 5
    - identifier: map
      name: Sitemap
      url: /map
      weight: 6
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
permalinks:
  /: /:filename/
  blog: /blog/:year/:month/:day/:slug/
timeout: 2m
