baseURL: "https://percona.community/"
disablePathToLower: false
languageCode: "en-us"
title: "Percona Community"
copyright: |
  Â© Percona Community. MySQL, InnoDB, MariaDB and MongoDB are trademarks of their respective owners.
disableHugoGeneratorInject: true
params:
  favicon: superhero.png
  images:
    - contribute.jpg
taxonomies:
  tag: tags
  category: categories
  contributor_type: "contributor_type"
  contributor_tag: "contributor_tag"
social:
  twitter: Percona
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 1
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: monokai
    tabWidth: 4
menu:
  main:
    - identifier: contribute
      name: Contribute
      url: /contribute
      weight: 1
    - identifier: blog
      name: Blog
      url: /blog
      weight: 2
    - identifier: forum
      name: Forum
      url: https://forums.percona.com/
      weight: 3
    - identifier: events
      name: Events
      url: /events
      weight: 4
    - identifier: databases
      name: Databases
      url: 
      weight: 5
    - identifier: projects
      name: Projects
      url: /projects
      weight: 6
    - identifier: other
      name: ...
      url: 
      weight: 7

    - identifier: MySQL
      name: MySQL
      url: /mysql
      parent: databases
      weight: 1
    - identifier: PostgreSQL
      name: PostgreSQL
      url: /postgresql
      parent: databases
      weight: 2
    - identifier: MongoDB
      name: MongoDB
      url: /mongodb
      parent: databases
      weight: 3

    - identifier: kubernetes
      name: Kubernetes Operators
      url: /projects/operators/
      parent: projects
      weight: 4
    - identifier: everest
      name: Percona Everest
      url: /projects/everest
      parent: projects
      weight: 5
    - identifier: pmm
      name: Percona Monitoring and Management
      url: /projects/pmm/
      parent: projects
      weight: 6
    - identifier: subtoolkit
      name: Percona Toolkit
      url: /projects/toolkit/
      parent: projects
      weight: 7
    - identifier: allprojects
      name: All projects
      url: /projects
      parent: projects
      weight: 8

    - identifier: communityevents
      name: Community Events
      url: /events
      parent: events
      weight: 1
    - identifier: speakers
      name: Speakers
      url: /speakers
      parent: events
      weight: 3

    - identifier: posts
      name: Posts
      url: /blog
      parent: blog
      weight: 1
    - identifier: authors
      name: Authors
      url: /authors
      parent: blog
      weight: 2

    - identifier: involved 
      name: How to Get Involved
      url: /contribute/how-to-get-involved
      parent: contribute
      weight: 1
    - identifier: coc
      name: Code of Conduct
      url: /contribute/coc
      parent: contribute
      weight: 2
    - identifier: opentopics
      name: Open Topics
      url: /contribute/opentopics
      parent: contribute
      weight: 3
    - identifier: articles
      name: Articles
      url: /contribute/articles
      parent: contribute
      weight: 4
    - identifier: youtube_playlists
      name: YouTube Playlists
      url: /contribute/youtube_playlists
      parent: contribute
      weight: 5
    - identifier: documentation
      name: Documentation
      url: /contribute/documentation
      parent: contribute
      weight: 6
    - identifier: surveys
      name: Testimonials & Surveys
      url: /contribute/testimonials
      parent: contribute
      weight: 7

    - identifier: videos
      name: Videos
      url: /contribute/videos
      parent: contribute
      weight: 9
    - identifier: dev
      name: Repositories and Artifacts
      url: /contribute/dev
      parent: contribute
      weight: 10

    - identifier: newsletter
      name: Community Newsletter
      url: /contribute/newsletter
      parent: other
      weight: 1
    - identifier: labs
      name: Percona Labs
      parent: other
      url: /labs
      weight: 2
    - identifier: open-source-database-hall-of-fame
      name: Open Source Database Hall of Fame
      url: /open-source-database-hall-of-fame
      parent: other
      weight: 3
    - identifier: dsto
      name: Dave Talks Open (Archive)
      url: /events/dave-stokes-talks-open-percona-live-2022/
      parent: other
      weight: 4
    - identifier: podcasts
      name: HOSS Talks (Archive)
      url: /podcasts
      parent: other
      weight: 5


  footer:
    - identifier: newsletter
      name: Community Newsletter
      url: /contribute/newsletter
      weight: 1
    - identifier: about
      name: About
      url: https://www.percona.com/about-percona
      weight: 2
    - identifier: legal
      name: Legal
      url: https://www.percona.com/legal
      weight: 3
    - identifier: contact
      name: Contact
      url: https://www.percona.com/about-percona/contact
      weight: 4
    - identifier: forums
      name: Forums
      url: https://forums.percona.com
      weight: 5
    - identifier: map
      name: Sitemap
      url: /map
      weight: 6
imaging:
  resampleFilter: lanczos
  quality: 60
  anchor: Center
permalinks:
  /: /:contentbasename/
  blog: /blog/:year/:month/:day/:slug/
timeout: 2m
caches:
  images:
    dir: :cacheDir/images
