baseURL: "https://percona.community/"
disablePathToLower: false
languageCode: "en-us"
title: "Percona Community"
copyright: |
  Â© Percona Community. MySQL, InnoDB, MariaDB and MongoDB are trademarks of their respective owners.
disableHugoGeneratorInject: true
taxonomies:
  tag: tags
  author: authors
social:
  twitter: Percona
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: monokai
    tabWidth: 4
menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog
      weight: -110
    - identifier: projects
      name: Projects
      url: /projects
      weight: -100
    - identifier: contribute
      name: Contribute
      url: /contribute
      weight: -90
    - identifier: forums
      name: Forums
      url: https://forums.percona.com
      weight: -80
    - identifier: discord
      name: Discord
      url: http://per.co.na/discord
      weight: -70

  footer:
    - identifier: about
      name: About
      url: https://www.percona.com/about-percona
      weight: 1
    - identifier: legal
      name: Legal
      url: https://www.percona.com/legal
      weight: 2
    - identifier: contact
      name: Contact
      url: https://www.percona.com/about-percona/contact
      weight: 3
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
permalinks:
  /: /:filename/
  blog: /blog/:year/:month/:day/:slug/
